# Generated by Django 5.2.17 on 2026-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_ACTIVATED', 'User activated'), ('USER_DELETED', 'User deleted'), ('TAHSILDAR_CREATED', 'Tahsildar created'), ('TAHSILDAR_UPDATED', 'Tahsildar updated'), ('TAHSILDAR_DEACTIVATED', 'Tahsildar deactivated'), ('RECORD_CREATED', 'Record created'), ('RECORD_UPDATED', 'Record updated'), ('RECORD_DEACTIVATED', 'Record deactivated'), ('RECORD_SUBMITTED', 'Record submitted'), ('RECORD_REVIEW_STARTED', 'Review started'), ('CORRECTION_REQUESTED', 'Correction requested'), ('RECORD_APPROVED', 'Record approved'), ('RECORD_FORWARDED', 'Record forwarded'), ('RECORD_FINALIZED', 'Record finalized'), ('PASSWORD_RESET', 'Password reset'), ('ROLE_CHANGED', 'Role changed'), ('TALUKA_CHANGED', 'Taluka changed')], db_index=True, max_length=40),
        ),
    ]
