# Generated by Django 5.2.17 on 2026-09-01 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('talukas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='correction_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CORRECTION_REQUIRED', 'Correction Required'), ('APPROVED', 'Approved'), ('FORWARDED', 'Forwarded'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('USER_UPDATED_RECORD', 'User updated record'), ('TAHSILDAR_UPDATED_RECORD', 'Tahsildar updated record'), ('RECORD_SUBMITTED', 'Record submitted'), ('RECORD_CORRECTION_REQUESTED', 'Correction requested'), ('RECORD_APPROVED', 'Record approved'), ('RECORD_FORWARDED', 'Record forwarded'), ('RECORD_FINALIZED', 'Record finalized')], max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='records.record')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talukas.taluka')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['record', 'timestamp'], name='records_rec_record__17853c_idx'), models.Index(fields=['action', 'timestamp'], name='records_rec_action_819ec3_idx')],
            },
        ),
    ]
