# Generated by Django 5.2.17 on 2026-09-01 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_approved_at_record_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='record',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='record',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ddo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ddo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AddField(
            model_name='record',
            name='gpf_account_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='record',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='record',
            name='subscriber_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='record',
            name='total_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='record',
            name='treasury',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='RecordWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('withdrawal_type', models.CharField(blank=True, max_length=100)),
                ('withdrawal_voucher_no', models.CharField(blank=True, max_length=50)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='records.record')),
            ],
            options={
                'ordering': ['-withdrawal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordMonthlyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, help_text='MM/YYYY format', max_length=7)),
                ('subscription', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refund_of_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_transactions', to='records.record')),
            ],
            options={
                'ordering': ['record', 'month'],
                'indexes': [models.Index(fields=['record', 'month'], name='records_rec_record__a6eed7_idx')],
                'unique_together': {('record', 'month')},
            },
        ),
    ]
